site_name: preconvert
theme: readthedocs
nav:
    - Home: index.md
    - Reference:
        - preconvert/index.md
        - preconvert/convert.md
        - preconvert/converters.md
        - preconvert/exceptions.md
        - preconvert/register.md
        - preconvert/output/index.md
