site_name: preconvert
theme: readthedocs
nav:
    - Home: index.md
    - Reference:
        - Preconvert: 'preconvert/index.md'
        - Convert: 'preconvert/convert.md'
        - Converters: 'preconvert/converters.md'
        - Exceptions: 'preconvert/exceptions.md'
        - Register: 'preconvert/register.md'
        - Output: 'preconvert/output/index.md'
        - JSON: 'preconvert/output/json.md'
        - SimpleJSON: 'preconvert/output/simplejson.md'
        - MsgPack: 'preconvert/output/msgpack.md'
        - BSON: 'preconvert/output/bson.md'
