site_name: preconvert
theme: readthedocs
nav:
    - Home: index.md
    - Reference:
        - __auto__/preconvert.md
        - __auto__/preconvert.convert.md
        - __auto__/preconvert.converters.md
        - __auto__/preconvert.exceptions.md
        - __auto__/preconvert.register.md
        - __auto__/preconvert.output.md
